baseURL = 'http://example.org/'
languageCode = 'de-CH'
title = 'This is a Test'
theme = 'docsy'
[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
